### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by BaxAndrei** [NamelessMC/Nameless-Modules#6]
I suggest to add an little and simple module for wiki, if server need it.

**Comment by KaspianDev** [comment]
+1

**Comment by CqldFire** [comment]
Someone has contacted me and this module is under development using the rules module as base code (but not by me).

**Comment by CqldFire** [comment]
This module has been added, can an admin please close the issue

**Comment by samerton** [comment]
https://namelessmc.com/resources/resource/145-wiki/
